/*
	Match.c
	-------
	
	here we define and set up the variables related to a Match (i.e. game settings for the current round)
	
	C Source File
	Created 11/15/2017; 11:46:48 AM
*/

// includes
#include "Main.h"
#include "Match.h"
#include "Worms.h"


// these are the default match settings. Eventually these should be read
// from a temporary settings file generated by the WWP executable

// the number of worms on each team, max 8
char Match_wormCount[2] = {6, 6};

// the gravestone icons to use for each time:
char Match_gravestones[2] = {0, 1};

// the heath worms should start at:
unsigned char Match_wormStartHealth = 100;

// is worm selection enabled?
char Match_allowWormSelection = TRUE;

// playing with artillery mode? (no movement allowed)
char Match_artilleryMode = FALSE;

// how long are turns, in seconds?
char Match_turnTime = 45; //45;

// mine settings: enabled? fuse length? duds enabled?
char Match_minesEnabled = TRUE;
char Match_mineFuseLength = 3;
char Match_dudMines = TRUE;

// allow worms to be strategically placed on the map at the game start
char Match_strategicPlacement = FALSE;

// playing with oil barrels?
char Match_oilDrumsEnabled = TRUE;

// allow each type of crate?
char Match_toolCratesEnabled = TRUE;
char Match_healthCratesEnabled = TRUE;
char Match_weaponCratesEnabled = TRUE;

// is sudden death mode enabled?
char Match_suddenDeathEnabled = TRUE;

// kind of map texture / land generation
char Match_mapType = MAP_SAND;
char Match_mapLandType = LAND_LAYERS;

// what things to draw
char Match_drawingFlags = DRAW_CLOUDS | DRAW_LEAVES | DRAW_MOUNTAINS;

// the default weapons for each worm in the match
char Match_defaultWeapons[65] = {
	1,9,9,9,9,1,1,3,5,1,2,1,9,
	1,1,3,9,9,2,1,3,2,1,1,1,9,
	1,5,1,9,1,1,1,3,2,1,1,1,3,
	1,1,2,1,9,1,1,1,2,1,1,1,1,
	1,1,1,2,9,1,1,1,2,1,1,1,1
};

// the current stock of weapons for each team								
short Match_teamWeapons[2][65] = {
	{
		1,9,9,9,9,1,1,3,5,1,2,1,9,
		1,1,3,9,9,2,1,3,2,1,1,1,9,
		1,5,1,9,1,1,1,3,2,1,1,1,3,
		1,1,2,1,9,1,1,1,2,1,1,1,1,
		1,1,1,2,9,1,1,1,2,1,1,1,1
	},
	{
		1,9,9,9,9,1,1,3,5,1,2,1,9,
		1,1,3,9,9,2,1,3,2,1,1,1,9,
		1,5,1,9,1,1,1,3,2,1,1,1,3,
		1,1,2,1,9,1,1,1,2,1,1,1,1,
		1,1,1,2,9,1,1,1,2,1,1,1,1
	},
	/*{
		1,9,9,9,9,1,1,3,5,0,2,0,9,
		0,1,3,9,9,2,1,3,2,0,1,0,9,
		0,5,0,9,1,1,0,3,2,0,0,0,3,
		0,0,2,0,9,0,0,1,2,0,0,0,0,
		1,0,0,2,9,0,0,0,2,0,0,0,0
	}*/
};
																		
// the names of each team
char Match_teamNames[2][10] = {"GMILLER\0", "LDEBROUX\0"};

// the names of each worm
char Match_wormNames[MAX_WORMS][12] = {"MCGUYVER\0", "SLINKYFISH\0", "BUB\0", "STUMPY\0", "MISTER CHEF\0", "GERTIE\0", "KOWALSKI\0", "MURPHY\0", "ZULU\0", "JEAN STAINS\0", "TITCHY\0", "MUSCLES\0", "THE VERT\0", "DARKNET\0", "SMOKESTACK\0", "ROPESY\0"};
