/*
	SpriteData.h
	------------
	Generated by makeSprites.js
*/

#ifndef SPRITEDATA_H
#define SPRITEDATA_H

extern const unsigned short spr_Check_Fill[];

extern const unsigned short spr_Check_Outline[];

extern const unsigned short spr_Close_Fill[];

extern const unsigned short spr_Close_Outline[];

extern const unsigned long spr_Cloud_Dark[];

extern const unsigned long spr_Cloud_Light[];

extern const unsigned long spr_Cloud_Mask[];

extern const unsigned short spr_CrateHealth[];

extern const unsigned short spr_CrateTool[];

extern const unsigned short spr_CrateWeapon[];

extern const unsigned char spr_CursorFillFlipped[];

extern const unsigned char spr_CursorOutlineFlipped[];

extern const unsigned short spr_Disabled_Mask[];

extern const unsigned short spr_Disabled_Outline[];

extern const unsigned char spr_Grave[];

extern const unsigned char spr_Grave2[];

extern const unsigned char spr_Grave3[];

extern const unsigned long spr_MenuCredits[];

extern const unsigned long spr_MenuGame[];

extern const unsigned long spr_MenuMatch[];

extern const unsigned long spr_MenuSettingsAndHelp[];

extern const unsigned long spr_MenuTeams[];

extern const unsigned long spr_MenuWeapons[];

extern const unsigned long spr_Menu_Mask[];

extern const unsigned char spr_NoSelectArrow[];

extern const unsigned short spr_OilDark[];

extern const unsigned short spr_OilLight[];

extern const unsigned short spr_OilMask[];

extern const unsigned short spr_Option_Artillery[];

extern const unsigned char spr_Option_DudSmoke[];

extern const unsigned short spr_Option_HealthHead[];

extern const unsigned short spr_Option_HealthValues[];

extern const unsigned short spr_Option_Mine[];

extern const unsigned short spr_Option_Timer[];

extern const unsigned short spr_Parachute[];

extern const unsigned char spr_remote[];

extern const unsigned char spr_remoteMask[];

extern const unsigned short spr_SelectionArrowFrame1[];

extern const unsigned short spr_SelectionArrowFrame2[];

extern const unsigned long spr_TeamTab[];

extern const unsigned short spr_weaponSelect[];

#define NUM_WEAPONS 76
extern const unsigned short spr_weapons[][11];

extern const unsigned long tex_Ground2[];

extern const unsigned long tex_Ground3[];

extern const unsigned short worm_IDLE_Outline[];


#endif /* SPRITEDATA_H */
