/*
	SpriteData.h
	------------
	Generated by makeSprites.js
*/

#ifndef SPRITEDATA_H
#define SPRITEDATA_H

extern const unsigned long settingsIconBox[];

extern const unsigned short spr_Check_Fill[];

extern const unsigned short spr_Check_Outline[];

extern const unsigned short spr_Close_Fill[];

extern const unsigned short spr_Close_Outline[];

extern const unsigned long spr_Cloud_Dark[];

extern const unsigned long spr_Cloud_Light[];

extern const unsigned long spr_Cloud_Mask[];

extern const unsigned short spr_CrateHealth[];

extern const unsigned short spr_CrateTool[];

extern const unsigned short spr_CrateWeapon[];

extern const unsigned char spr_CursorFillFlipped[];

extern const unsigned char spr_CursorOutlineFlipped[];

extern const unsigned short spr_Disabled_Mask[];

extern const unsigned short spr_Disabled_Outline[];

extern const unsigned char spr_Grave[];

extern const unsigned char spr_Grave2[];

extern const unsigned char spr_Grave3[];

extern const unsigned char spr_Infinite[];

extern const unsigned long spr_MenuBorder[];

extern const unsigned long spr_MenuCredits[];

extern const unsigned long spr_MenuGame[];

extern const unsigned long spr_MenuMatch[];

extern const unsigned long spr_MenuSettingsAndHelp[];

extern const unsigned long spr_MenuTeams[];

extern const unsigned long spr_MenuWeapons[];

extern const unsigned long spr_Menu_Mask[];

extern const unsigned short spr_NoSelectArrow[];

extern const unsigned short spr_OilDark[];

extern const unsigned short spr_OilLight[];

extern const unsigned short spr_OilMask[];

extern const unsigned short spr_Option_Artillery[];

extern const unsigned short spr_Option_DudSmoke_Dark[];

extern const unsigned short spr_Option_DudSmoke_Light[];

#define NUM_OPTION_HEALTH 3
extern const unsigned short spr_Option_Health[][14];

extern const unsigned short spr_Option_MineBlank_Dark[];

extern const unsigned short spr_Option_MineBlank_Light[];

#define NUM_OPTION_MINEDARK 5
extern const unsigned short spr_Option_MineDark[][14];

#define NUM_OPTION_MINELIGHT 5
extern const unsigned short spr_Option_MineLight[][14];

extern const unsigned short spr_Option_PlaceWorms[];

#define NUM_OPTION_TIMER 3
extern const unsigned short spr_Option_Timer[][14];

extern const unsigned short spr_SelectionArrowFrame1[];

extern const unsigned short spr_SelectionArrowFrame2[];

extern const unsigned short spr_SuddenDeath[];

extern const unsigned long spr_TeamTab[];

extern const unsigned long spr_TeamTabR[];

#define NUM_TITLEDARK 5
extern const unsigned long spr_TitleDark[][100];

#define NUM_TITLELIGHT 5
extern const unsigned long spr_TitleLight[][100];

extern const unsigned short spr_Toggle[];

extern const unsigned short spr_weaponSelect[];

#define NUM_WEAPONS 65
extern const unsigned short spr_weapons[][11];

extern const unsigned long tex_Ground1[];

extern const unsigned long tex_Ground2[];

extern const unsigned long tex_Ground3[];

extern const unsigned short worm_IDLE_Mask[];

extern const unsigned short worm_IDLE_Outline[];


#endif /* SPRITEDATA_H */
