/*
	SpriteData.h
	------------
	Generated by makeSprites.js
*/

#ifndef SPRITEDATA_H
#define SPRITEDATA_H

extern const unsigned long spi_CandleCake_Dark[];

extern const unsigned long spi_CandleCake_Light[];

extern const unsigned char sprDudSmoke[];

extern const unsigned char spr_chargeLarge[];

extern const unsigned char spr_chargeMed[];

extern const unsigned char spr_chargeSmall[];

extern const unsigned short spr_Check_Fill[];

extern const unsigned short spr_Check_Outline[];

extern const unsigned long spr_Cloud_Dark[];

extern const unsigned long spr_Cloud_Light[];

extern const unsigned long spr_Cloud_Mask[];

extern const unsigned short spr_CrateHealth[];

extern const unsigned short spr_CrateTool[];

extern const unsigned short spr_CrateWeapon[];

extern const unsigned char spr_CrossHair[];

extern const unsigned char spr_CursorFill[];

extern const unsigned char spr_CursorFillFlipped[];

extern const unsigned char spr_CursorOutline[];

extern const unsigned char spr_CursorOutlineFlipped[];

extern const unsigned long spr_Donkey_Dark[];

extern const unsigned long spr_Donkey_Light[];

extern const unsigned long spr_Donkey_Mask[];

extern const unsigned char spr_Fuel[];

#define NUM_GRAVE 3
extern const unsigned char spr_Grave[][12];

extern const unsigned char spr_launcher[];

extern const unsigned short spr_Leaf[];

extern const unsigned long spr_MB_Dark[];

extern const unsigned long spr_MB_Light[];

extern const unsigned long spr_MB_Mask[];

extern const unsigned char spr_Mine_Dark[];

extern const unsigned char spr_Mine_Light[];

#define NUM_MOUNTAIN 5
extern const unsigned long spr_Mountain[][38];

extern const unsigned char spr_NoSelectArrow[];

extern const unsigned short spr_OilDark[];

extern const unsigned short spr_OilLight[];

extern const unsigned short spr_OilMask[];

extern const unsigned short spr_Parachute[];

extern const unsigned char spr_remote[];

extern const unsigned char spr_remoteMask[];

extern const unsigned short spr_selectedWeaponBox[];

extern const unsigned short spr_selectedWeaponBoxMask[];

extern const unsigned short spr_SelectionArrowFrame1[];

extern const unsigned short spr_SelectionArrowFrame2[];

extern const unsigned short spr_timerBlink[];

extern const unsigned short spr_timerBorder[];

extern const unsigned short spr_timerMask[];

extern const unsigned long spr_tinyFont[];

extern const unsigned long spr_Water_Dark[];

extern const unsigned long spr_Water_Light[];

extern const unsigned long spr_Water_Mask[];

extern const unsigned short spr_weaponSelect[];

#define NUM_WEAPONS 76
extern const unsigned short spr_weapons[][11];

extern const unsigned long spr_WindMeter[];

extern const unsigned long spr_WindMeter_Mask[];

extern const unsigned char spr_XSpot[];

extern const unsigned char spr_XSpotMask[];

extern const unsigned long tex_Ground1[];

extern const unsigned long tex_Ground2[];

extern const unsigned long tex_Ground3[];

/* --- Worms Data --- */

extern const unsigned short worm_BACKFLIP1_Outline[];

extern const unsigned short worm_BACKFLIP2_Outline[];

extern const unsigned short worm_BACKFLIP3_Outline[];

extern const unsigned short worm_BACKFLIP4_Outline[];

extern const unsigned short worm_BUNGEE_Outline[];

extern const unsigned short worm_CHUTE_Outline[];

extern const unsigned short worm_DRILL_Outline[];

extern const unsigned short worm_FROZEN_Light[];
extern const unsigned short worm_FROZEN_Dark[];

extern const unsigned short worm_IDLE_Outline[];

extern const unsigned short worm_IDLE2_Outline[];

extern const unsigned short worm_JETPACK_Outline[];

extern const unsigned short worm_JUMP_Outline[];

extern const unsigned short worm_ROPE135_Outline[];

extern const unsigned short worm_ROPE45_Outline[];

extern const unsigned short worm_TNT1_Outline[];

extern const unsigned short worm_TNT2_Outline[];

extern const unsigned short worm_TORCH_Outline[];

extern const unsigned short worm_WALK_Outline[];

#define NUM_WORM_SPRITES 37
#define WORM_FLIP_BUFFER_SIZE 537
#define WORM_GENERATED_MASK_BUFFER_SIZE 262

#define WORM_BACKFLIP1_MASK 0
#define WORM_BACKFLIP1_LIGHT 1
#define WORM_BACKFLIP1_DARK 1
#define WORM_BACKFLIP2_MASK 2
#define WORM_BACKFLIP2_LIGHT 3
#define WORM_BACKFLIP2_DARK 3
#define WORM_BACKFLIP3_MASK 4
#define WORM_BACKFLIP3_LIGHT 5
#define WORM_BACKFLIP3_DARK 5
#define WORM_BACKFLIP4_MASK 6
#define WORM_BACKFLIP4_LIGHT 7
#define WORM_BACKFLIP4_DARK 7
#define WORM_BUNGEE_MASK 8
#define WORM_BUNGEE_LIGHT 9
#define WORM_BUNGEE_DARK 9
#define WORM_CHUTE_MASK 10
#define WORM_CHUTE_LIGHT 11
#define WORM_CHUTE_DARK 11
#define WORM_DRILL_MASK 12
#define WORM_DRILL_LIGHT 13
#define WORM_DRILL_DARK 13
#define WORM_FROZEN_MASK 14
#define WORM_FROZEN_LIGHT 15
#define WORM_FROZEN_DARK 16
#define WORM_IDLE_MASK 17
#define WORM_IDLE_LIGHT 18
#define WORM_IDLE_DARK 18
#define WORM_IDLE2_MASK 19
#define WORM_IDLE2_LIGHT 20
#define WORM_IDLE2_DARK 20
#define WORM_JETPACK_MASK 21
#define WORM_JETPACK_LIGHT 22
#define WORM_JETPACK_DARK 22
#define WORM_JUMP_MASK 23
#define WORM_JUMP_LIGHT 24
#define WORM_JUMP_DARK 24
#define WORM_ROPE135_MASK 25
#define WORM_ROPE135_LIGHT 26
#define WORM_ROPE135_DARK 26
#define WORM_ROPE45_MASK 27
#define WORM_ROPE45_LIGHT 28
#define WORM_ROPE45_DARK 28
#define WORM_TNT1_MASK 29
#define WORM_TNT1_LIGHT 30
#define WORM_TNT1_DARK 30
#define WORM_TNT2_MASK 31
#define WORM_TNT2_LIGHT 32
#define WORM_TNT2_DARK 32
#define WORM_TORCH_MASK 33
#define WORM_TORCH_LIGHT 34
#define WORM_TORCH_DARK 34
#define WORM_WALK_MASK 35
#define WORM_WALK_LIGHT 36
#define WORM_WALK_DARK 36
extern unsigned short* wormsSprites[];
extern const unsigned char wormSpriteHeights[];
extern const unsigned char wormSpriteTypes[];

#endif /* SPRITEDATA_H */
